/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.40
 * Generated at: 2025-05-21 13:11:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.nekomart.model.*;
import java.util.*;

public final class toys_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(7);
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("com.nekomart.model");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

    User user = (User) session.getAttribute("user");
    if (user == null) { response.sendRedirect("login.jsp"); return; }
    ToyLinkedList toys = com.nekomart.util.FileUtil.readToys();
    String selectedAge = request.getParameter("ageGroup");
    if (selectedAge != null && !selectedAge.isEmpty()) {
        // Filter toys by selected age group
        ToyLinkedList filteredToyList = new ToyLinkedList();
        for (Toy t : toys.getAll()) {
            if (t.getAgeGroup() == Integer.parseInt(selectedAge)) {
                filteredToyList.add(t);
            }
        }
        toys = filteredToyList;
    }

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Toys - NekoMart</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("    <style>\r\n");
      out.write("        body {\r\n");
      out.write("            background: url('images/Frontend/wallpaperflare.com_wallpaper.jpg') no-repeat center center fixed;\r\n");
      out.write("            background-size: cover;\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("        }\r\n");
      out.write("        .container.fade-in {\r\n");
      out.write("            background-color: rgba(34, 34, 34, 0.55);\r\n");
      out.write("            border: none;\r\n");
      out.write("            box-shadow: none;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            max-width: 1200px;\r\n");
      out.write("            padding: 2rem;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            border-radius: 16px;\r\n");
      out.write("        }\r\n");
      out.write("        .header {\r\n");
      out.write("            background: transparent;\r\n");
      out.write("            box-shadow: none;\r\n");
      out.write("            margin-bottom: 2rem;\r\n");
      out.write("        }\r\n");
      out.write("        .header-content {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            padding: 0 2rem;\r\n");
      out.write("            position: relative;\r\n");
      out.write("        }\r\n");
      out.write("        .header-left {\r\n");
      out.write("            flex: 1;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: flex-start;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("        }\r\n");
      out.write("        .header-center {\r\n");
      out.write("            flex: 1;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("        }\r\n");
      out.write("        .header-right {\r\n");
      out.write("            flex: 1;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: flex-end;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("        }\r\n");
      out.write("        .logo {\r\n");
      out.write("            font-size: 2.5rem;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            color: #ffb6c1;\r\n");
      out.write("            text-shadow: 2px 2px 8px #222, 0 0 2px #fff;\r\n");
      out.write("            margin-bottom: 1.5rem;\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("        .toy-card {\r\n");
      out.write("            background: rgba(34,34,34,0.80);\r\n");
      out.write("            border-radius: 16px;\r\n");
      out.write("            box-shadow: 0 2px 8px rgba(0,0,0,0.06);\r\n");
      out.write("            padding: 1rem;\r\n");
      out.write("            transition: transform 0.3s;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("        }\r\n");
      out.write("        .filters {\r\n");
      out.write("            background: rgba(34,34,34,0.55);\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            border-radius: 16px;\r\n");
      out.write("            box-shadow: 0 2px 8px rgba(0,0,0,0.06);\r\n");
      out.write("        }\r\n");
      out.write("        .admin-section {\r\n");
      out.write("            background: rgba(34,34,34,0.80);\r\n");
      out.write("            border-radius: 16px;\r\n");
      out.write("            box-shadow: 0 2px 8px rgba(0,0,0,0.06);\r\n");
      out.write("        }\r\n");
      out.write("        .toy-image {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 200px;\r\n");
      out.write("            object-fit: cover;\r\n");
      out.write("            border-radius: var(--border-radius);\r\n");
      out.write("            transition: transform 0.3s;\r\n");
      out.write("        }\r\n");
      out.write("        .toy-card:hover {\r\n");
      out.write("            transform: translateY(-5px);\r\n");
      out.write("        }\r\n");
      out.write("        .toy-card:hover .toy-image {\r\n");
      out.write("            transform: scale(1.05);\r\n");
      out.write("        }\r\n");
      out.write("        .toy-grid {\r\n");
      out.write("            display: grid;\r\n");
      out.write("            grid-template-columns: repeat(auto-fill, minmax(250px, 1fr));\r\n");
      out.write("            gap: 2rem;\r\n");
      out.write("            padding: 2rem 0;\r\n");
      out.write("        }\r\n");
      out.write("        .toy-name {\r\n");
      out.write("            font-size: 1.2rem;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            color: #f5f5f5;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            margin: 1rem 0;\r\n");
      out.write("            display: block;\r\n");
      out.write("        }\r\n");
      out.write("        .toy-name:hover {\r\n");
      out.write("            color: var(--primary-color);\r\n");
      out.write("        }\r\n");
      out.write("        .rating {\r\n");
      out.write("            color: var(--secondary-color);\r\n");
      out.write("            font-size: 1.1rem;\r\n");
      out.write("            margin: 0.5rem 0;\r\n");
      out.write("        }\r\n");
      out.write("        .star {\r\n");
      out.write("            color: var(--secondary-color);\r\n");
      out.write("        }\r\n");
      out.write("        .toy-price {\r\n");
      out.write("            font-size: 1.3rem;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            color: var(--primary-color);\r\n");
      out.write("            margin: 0.5rem 0;\r\n");
      out.write("        }\r\n");
      out.write("        .toy-age {\r\n");
      out.write("            background-color: #333;\r\n");
      out.write("            padding: 0.3rem 0.6rem;\r\n");
      out.write("            border-radius: var(--border-radius);\r\n");
      out.write("            font-size: 0.9rem;\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            margin: 0.5rem 0;\r\n");
      out.write("            color: #f5f5f5;\r\n");
      out.write("        }\r\n");
      out.write("        .admin-section h3 {\r\n");
      out.write("            color: var(--primary-color);\r\n");
      out.write("            margin-bottom: 1rem;\r\n");
      out.write("        }\r\n");
      out.write("        .admin-form {\r\n");
      out.write("            display: grid;\r\n");
      out.write("            gap: 1rem;\r\n");
      out.write("            max-width: 500px;\r\n");
      out.write("        }\r\n");
      out.write("        .action-buttons {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            gap: 0.5rem;\r\n");
      out.write("            margin-top: 1rem;\r\n");
      out.write("        }\r\n");
      out.write("        .nav-menu {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: row;\r\n");
      out.write("            gap: 3rem;\r\n");
      out.write("            list-style: none;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("        }\r\n");
      out.write("        .nav-menu li {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("        }\r\n");
      out.write("        .nav-menu a {\r\n");
      out.write("            color: #222;\r\n");
      out.write("            background: #ffb6c1;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            padding: 0.5rem 2rem;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            font-size: 1.1rem;\r\n");
      out.write("            transition: background 0.2s;\r\n");
      out.write("            display: inline-flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            min-width: 160px;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("        }\r\n");
      out.write("        .nav-menu a:hover {\r\n");
      out.write("            background: #ff69b4;\r\n");
      out.write("        }\r\n");
      out.write("        .nav-menu form {\r\n");
      out.write("            display: none;\r\n");
      out.write("        }\r\n");
      out.write("        .bottom-buttons {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: row;\r\n");
      out.write("            gap: 1.2rem;\r\n");
      out.write("            margin-top: 2.5rem;\r\n");
      out.write("        }\r\n");
      out.write("        .bottom-buttons .btn {\r\n");
      out.write("            display: inline-flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            min-width: 160px;\r\n");
      out.write("            height: 48px;\r\n");
      out.write("            padding: 0 2rem;\r\n");
      out.write("            font-size: 1.1rem;\r\n");
      out.write("            font-family: inherit;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            border: none;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("            line-height: 1;\r\n");
      out.write("            vertical-align: middle;\r\n");
      out.write("            background: #ffb6c1;\r\n");
      out.write("            color: #222;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            transition: background 0.2s;\r\n");
      out.write("        }\r\n");
      out.write("        .bottom-buttons .btn:hover {\r\n");
      out.write("            background: #ff69b4;\r\n");
      out.write("        }\r\n");
      out.write("        .btn, .btn-secondary, .btn-danger {\r\n");
      out.write("            display: inline-flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            min-width: 120px;\r\n");
      out.write("            height: 40px;\r\n");
      out.write("            padding: 0 1.5rem;\r\n");
      out.write("            font-size: 1.05rem;\r\n");
      out.write("            font-family: inherit;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            border: none;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("            line-height: 1;\r\n");
      out.write("            vertical-align: middle;\r\n");
      out.write("            background: #ffb6c1;\r\n");
      out.write("            color: #222;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            transition: background 0.2s;\r\n");
      out.write("        }\r\n");
      out.write("        .btn:hover, .btn-secondary:hover, .btn-danger:hover {\r\n");
      out.write("            background: #ff69b4;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"container fade-in\">\r\n");
      out.write("        <header class=\"header\">\r\n");
      out.write("            <div class=\"header-content\">\r\n");
      out.write("                <div class=\"header-left\">\r\n");
      out.write("                    <nav>\r\n");
      out.write("                        <ul class=\"nav-menu\">\r\n");
      out.write("                            <li><a href=\"toys.jsp\" class=\"btn btn-secondary\">Toys</a></li>\r\n");
      out.write("                            <li><a href=\"cart.jsp\" class=\"btn btn-secondary\">Cart</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </nav>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"header-center\">\r\n");
      out.write("                    <a href=\"index.jsp\" class=\"logo\">NekoMart</a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"header-right\">\r\n");
      out.write("                    <form action=\"user\" method=\"post\" style=\"margin-left:auto;\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"action\" value=\"logout\">\r\n");
      out.write("                        <button type=\"submit\" class=\"btn btn-secondary\" style=\"min-width:100px;\">Logout</button>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </header>\r\n");
      out.write("\r\n");
      out.write("        <form action=\"toys.jsp\" method=\"get\">\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <label for=\"ageGroup\" style=\"color: #ffb6c1; font-weight: bold;\">Filter by Age Group:</label>\r\n");
      out.write("                <select name=\"ageGroup\" id=\"ageGroup\" class=\"form-control\">\r\n");
      out.write("                    <option value=\"\">All Ages</option>\r\n");
      out.write("                    <option value=\"3\" ");
      out.print( "3".equals(selectedAge) ? "selected" : "" );
      out.write(">3+</option>\r\n");
      out.write("                    <option value=\"7\" ");
      out.print( "7".equals(selectedAge) ? "selected" : "" );
      out.write(">7+</option>\r\n");
      out.write("                    <option value=\"12\" ");
      out.print( "12".equals(selectedAge) ? "selected" : "" );
      out.write(">12+</option>\r\n");
      out.write("                </select>\r\n");
      out.write("            </div>\r\n");
      out.write("            <button class=\"btn btn-secondary\" type=\"submit\">Filter</button>\r\n");
      out.write("        </form>\r\n");
      out.write("\r\n");
      out.write("        <form action=\"toy\" method=\"post\" style=\"margin-top: 1rem;\">\r\n");
      out.write("            <input type=\"hidden\" name=\"action\" value=\"sort\">\r\n");
      out.write("            <button class=\"btn btn-secondary\" type=\"submit\">Sort by Age Group</button>\r\n");
      out.write("        </form>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"toy-grid\">\r\n");
      out.write("            ");
 for (Toy t : toys.getAll()) {
                double avgRating = com.nekomart.util.FileUtil.getAverageRating(t.getId());
            
      out.write("\r\n");
      out.write("            <div class=\"toy-card\">\r\n");
      out.write("                ");
 if (t.getImage() != null && !t.getImage().isEmpty()) { 
      out.write("\r\n");
      out.write("                    <img src=\"images/toys/");
      out.print( t.getImage() );
      out.write("\" alt=\"");
      out.print( t.getName() );
      out.write("\" class=\"toy-image\">\r\n");
      out.write("                ");
 } else { 
      out.write("\r\n");
      out.write("                    <img src=\"images/toys/default.jpg\" alt=\"No image available\" class=\"toy-image\">\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("                <a href=\"toy-details.jsp?id=");
      out.print( t.getId() );
      out.write("\" class=\"toy-name\">");
      out.print( t.getName() );
      out.write("</a>\r\n");
      out.write("                <div class=\"rating\">\r\n");
      out.write("                    ");
 for (int i = 1; i <= 5; i++) { 
      out.write("\r\n");
      out.write("                        <span class=\"star\">");
      out.print( i <= avgRating ? "★" : "☆" );
      out.write("</span>\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("                    (");
      out.print( String.format("%.1f", avgRating) );
      out.write(")\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"toy-price\">$");
      out.print( t.getPrice() );
      out.write("</div>\r\n");
      out.write("                <div class=\"toy-age\">Age: ");
      out.print( t.getAgeGroup() );
      out.write("+</div>\r\n");
      out.write("                <div class=\"action-buttons\">\r\n");
      out.write("                    <form action=\"cart\" method=\"post\" style=\"flex: 1;\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"action\" value=\"add\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"id\" value=\"");
      out.print( t.getId() );
      out.write("\">\r\n");
      out.write("                        <button class=\"btn\" type=\"submit\" style=\"width: 100%;\">Add to Cart</button>\r\n");
      out.write("                    </form>\r\n");
      out.write("                    ");
 if ("admin".equals(user.getRole())) { 
      out.write("\r\n");
      out.write("                    <form action=\"toy\" method=\"post\" style=\"flex: 1;\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"action\" value=\"delete\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"id\" value=\"");
      out.print( t.getId() );
      out.write("\">\r\n");
      out.write("                        <button class=\"btn btn-danger\" type=\"submit\" style=\"width: 100%;\">Delete</button>\r\n");
      out.write("                    </form>\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        ");
 if ("admin".equals(user.getRole())) { 
      out.write("\r\n");
      out.write("        <div class=\"admin-section\">\r\n");
      out.write("            <h3>Add New Toy</h3>\r\n");
      out.write("            <form action=\"toy\" method=\"post\" enctype=\"multipart/form-data\" class=\"admin-form\">\r\n");
      out.write("                <input type=\"hidden\" name=\"action\" value=\"add\">\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <input type=\"text\" name=\"name\" placeholder=\"Toy Name\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <input type=\"text\" name=\"description\" placeholder=\"Description\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <input type=\"number\" step=\"0.01\" name=\"price\" placeholder=\"Price\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <input type=\"number\" name=\"ageGroup\" placeholder=\"Age Group\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <input type=\"file\" name=\"image\" accept=\"image/*\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <button class=\"btn btn-secondary\" type=\"submit\">Add Toy</button>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
